FROM cimg/android:2022.04-browsers

WORKDIR /home/circleci/project
USER circleci

RUN npm install cordova@11
ENV PATH=$PATH:/home/circleci/project/node_modules/cordova/bin/
ENV ENVIRONMENT=staging
RUN cordova telemetry off
COPY --chown=circleci . /home/circleci/project/
RUN node --version \
  && cordova --version \
  && gradle -version \
  && java -version

# docker build -f Dockerfile-cordova -t goodcity:latest .
# docker run -it goodcity:latest /bin/bash
# cordova build android --debug --device

# ADVANCED USAGE KEEPS IMAGE RUNNING TO MAINTAIN GRADLE CACHE
# ENVIRONMENT=staging EMBER_CLI_CORDOVA=1 yarn run ember build
# cd cordova
# ln -s ../dist www
# cordova platform add android@11
# cd ..
# docker run -i --rm -v `pwd`/dist/:/home/circleci/project/dist/ -v `pwd`/cordova:/home/circleci/project/cordova/ -w /home/circleci/project/cordova/ -u root -t goodcity:latest /bin/bash
#   cordova build android --debug --device
# App located in `pwd`/cordova/platforms/android/app/build/outputs/apk/debug/app-debug.apk
